### ISSUE TITLE
'Show in Menu' option not saving

### ISSUE THREAD

**Issue by jnki** [anchorcms/anchor-cms#1063]
### Summary

Just upgraded to 0.12.1 a couple days ago.

When I create a new page and try to disable the 'show in menu' option, it does not save.

Thanks for helping

### Expected Behaviour

Create a page.

Deselect the 'Show in Menu' option

Page should not be visible in menu

### Actual Behaviour

Create a page.

Deselect 'Show in Menu' option and press save.

Page is still in menu, and option 'Show in Menu' has reverted back.

- Anchor version: 0.12.1

**Comment by daviddarnes** [comment]
This isn't good, thanks for reporting it @jnki.

**Comment by CrackerStealth** [comment]
I ran into this issue as well after an upgrade. It appears to have been fixed since 0.12.1 with this commit: 3336da88115f582c7faf5cef74960bbdc4cc5fcf

**Comment by daviddarnes** [comment]
@CrackerStealth oh really? Well that's the same version @jnki is using when they encountered the issue.

**Comment by georg90** [comment]
Same here with 0.12.1

**Comment by CraigChilds94** [comment]
This is fixed, it's just not released yet 💃

**Comment by daviddarnes** [comment]
This still appears to be an issue, as mentioned by @bmuessig in #1151

**Comment by treechime** [comment]
Yep, also experiencing this.

**Comment by TheBrenny** [comment]
I witnessed this once, but as @CraigChilds94 said, it's been fixed. Might see if we can push the fix to public, @daviddarnes?

**Comment by daviddarnes** [comment]
@TheBrenny sure, I'm not familiar with how though 😅
